dist: xenial

services:
    - docker

language: python
python:
    - "3.6"

env:
    - SCVERSION="stable"

before_install:
    - docker pull quay.io/coreos-assembler/coreos-assembler:latest
    - docker build -t coreos-assembler-test -f Dockerfile.dev .

script:
    - docker run -ti --rm --entrypoint "/usr/bin/sudo" coreos-assembler-test:latest su -c "cd /root/containerbuild/; make check"
    - docker run -ti --rm --entrypoint "/usr/bin/sudo" coreos-assembler-test:latest su -c "cd /root/containerbuild/; make unittest"

notifications:
  email: false
